from PyQt6.QtGui import QColor
from plugins.common.config_factory import generate_base_config

PROBLEM_TAG_WARNING = "ZMC_TAG_WARNING"
PROBLEM_WIDTH_EXCEEDED = "ZMC_WIDTH_EXCEEDED"
PROBLEM_SHORT_LINE = "ZMC_SHORT_LINE"
PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY = "ZMC_EMPTY_ODD_SUBLINE_DISPLAY"
PROBLEM_SINGLE_WORD_SUBLINE = "ZMC_SINGLE_WORD_SUBLINE"
PROBLEM_SINGLE_WORD_SUBLINE_NON_START = "ZMC_SINGLE_WORD_SUBLINE_NON_START"
PROBLEM_BAD_SPACING = "ZMC_BAD_SPACING"
PROBLEM_MISSING_ICON_SPACING = "ZMC_MISSING_ICON_SPACING"

PRIORITY_WIDTH_EXCEEDED = 1
PRIORITY_TAG_CRITICAL = 2
PRIORITY_TAG_WARNING = 3
PRIORITY_EMPTY_ODD = 4
PRIORITY_SINGLE_WORD_SUBLINE = 5
PRIORITY_SINGLE_WORD_SUBLINE_NON_START = 4
PRIORITY_SHORT_LINE = 6
PRIORITY_DEFAULT = 99

COLOR_CRITICAL_TAG = QColor(255, 192, 203, 100)
COLOR_WARNING_TAG = QColor(200, 200, 200, 150)
COLOR_WIDTH_EXCEEDED = QColor(255, 0, 0, 100)
COLOR_EMPTY_ODD = QColor(255, 165, 0, 180)
COLOR_SHORT_LINE = QColor(0, 200, 0, 100)
COLOR_SINGLE_WORD_SUBLINE = QColor(0, 0, 255, 120)
COLOR_SINGLE_WORD_SUBLINE_NON_START = QColor(139, 69, 19, 120)

# Default number of lines per page
DEFAULT_LINES_PER_PAGE = 4

COLOR_MARKER_DEFINITIONS = {
    "red": "Критична помилка або потребує повної перевірки",
    "green": "Перевірено, помилок немає",
    "blue": "Викликає сумніви або потребує уточнення"
}

CONTROL_CODES = ["\\n", "\\p", "·"]

overrides = {
    "priorities": {
        "WIDTH_EXCEEDED": PRIORITY_WIDTH_EXCEEDED,
        "TAG_WARNING": PRIORITY_TAG_WARNING,
        "EMPTY_ODD_SUBLINE_DISPLAY": PRIORITY_EMPTY_ODD,
        "SINGLE_WORD_SUBLINE": PRIORITY_SINGLE_WORD_SUBLINE,
        "SINGLE_WORD_SUBLINE_NON_START": PRIORITY_SINGLE_WORD_SUBLINE_NON_START,
        "SHORT_LINE": PRIORITY_SHORT_LINE,
    },
    "colors": {
        "TAG_WARNING": COLOR_WARNING_TAG,
        "WIDTH_EXCEEDED": COLOR_WIDTH_EXCEEDED,
        "EMPTY_ODD_SUBLINE_DISPLAY": COLOR_EMPTY_ODD,
        "SHORT_LINE": COLOR_SHORT_LINE,
        "SINGLE_WORD_SUBLINE": COLOR_SINGLE_WORD_SUBLINE,
        "SINGLE_WORD_SUBLINE_NON_START": COLOR_SINGLE_WORD_SUBLINE_NON_START,
    },
    "problem_definitions": {
        "EMPTY_ODD_SUBLINE_DISPLAY": {
            "name": "Empty First Line of Page",
            "description": "The first line of a page (1, N+1, 2N+1, ...) is empty or contains '0'."
        }
    }
}

PROBLEM_DEFINITIONS, DEFAULT_DETECTION_SETTINGS, DEFAULT_AUTOFIX_SETTINGS = generate_base_config(
    "ZMC", overrides=overrides
)