from PyQt6.QtGui import QColor
from plugins.common.config_factory import generate_base_config

PROBLEM_TAG_WARNING = "ZWW_TAG_WARNING"
PROBLEM_WIDTH_EXCEEDED = "ZWW_WIDTH_EXCEEDED"
PROBLEM_SHORT_LINE = "ZWW_SHORT_LINE"
PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY = "ZWW_EMPTY_ODD_SUBLINE_DISPLAY"
PROBLEM_SINGLE_WORD_SUBLINE = "ZWW_SINGLE_WORD_SUBLINE" 
PROBLEM_SINGLE_WORD_SUBLINE_NON_START = "ZWW_SINGLE_WORD_SUBLINE_NON_START"
PROBLEM_EMPTY_FIRST_LINE_OF_PAGE = "ZWW_EMPTY_FIRST_LINE_OF_PAGE"
PROBLEM_BAD_SPACING = "ZWW_BAD_SPACING"
PROBLEM_MISSING_ICON_SPACING = "ZWW_MISSING_ICON_SPACING"

PRIORITY_TAG_CRITICAL = 1 
PRIORITY_TAG_WARNING = 2
PRIORITY_WIDTH_EXCEEDED = 3
PRIORITY_EMPTY_ODD = 4
PRIORITY_EMPTY_FIRST_LINE = 5
PRIORITY_SINGLE_WORD_SUBLINE = 6 
PRIORITY_SINGLE_WORD_SUBLINE_NON_START = 5
PRIORITY_SHORT_LINE = 7
PRIORITY_DEFAULT = 99

COLOR_CRITICAL_TAG = QColor(255, 192, 203, 100)
COLOR_WARNING_TAG = QColor(200, 200, 200, 150)
COLOR_WIDTH_EXCEEDED = QColor(255, 0, 0, 100)
COLOR_EMPTY_ODD = QColor(255, 165, 0, 180)
COLOR_SHORT_LINE = QColor(0, 200, 0, 100)
COLOR_SINGLE_WORD_SUBLINE = QColor(0, 0, 255, 120) 
COLOR_SINGLE_WORD_SUBLINE_NON_START = QColor(139, 69, 19, 120)

custom_problems = {}

overrides = {
    "priorities": {
        "TAG_WARNING": PRIORITY_TAG_WARNING,
        "WIDTH_EXCEEDED": PRIORITY_WIDTH_EXCEEDED,
        "EMPTY_ODD_SUBLINE_DISPLAY": PRIORITY_EMPTY_ODD,
        "SINGLE_WORD_SUBLINE": PRIORITY_SINGLE_WORD_SUBLINE,
        "SINGLE_WORD_SUBLINE_NON_START": PRIORITY_SINGLE_WORD_SUBLINE_NON_START,
        "SHORT_LINE": PRIORITY_SHORT_LINE,
    },
    "colors": {
        "TAG_WARNING": COLOR_WARNING_TAG,
        "WIDTH_EXCEEDED": COLOR_WIDTH_EXCEEDED,
        "EMPTY_ODD_SUBLINE_DISPLAY": COLOR_EMPTY_ODD,
        "SHORT_LINE": COLOR_SHORT_LINE,
        "SINGLE_WORD_SUBLINE": COLOR_SINGLE_WORD_SUBLINE,
        "SINGLE_WORD_SUBLINE_NON_START": COLOR_SINGLE_WORD_SUBLINE_NON_START,
    }
}

PROBLEM_DEFINITIONS, DEFAULT_DETECTION_SETTINGS, DEFAULT_AUTOFIX_SETTINGS = generate_base_config(
    "ZWW", overrides=overrides, custom_problems=custom_problems
)