# core/context.py
from typing import Protocol, Optional, Any, Dict, List, Tuple, Set, TYPE_CHECKING
from PyQt6.QtWidgets import QStatusBar, QWidget, QListWidget, QComboBox, QSpinBox, QPushButton
from PyQt6.QtGui import QAction

if TYPE_CHECKING:
    from core.state_manager import StateManager
    from core.data_store import AppDataStore
    from core.project_manager import ProjectManager
    from core.settings_manager import SettingsManager
    from core.data_state_processor import DataStateProcessor
    from core.undo_manager import UndoManager
    from core.spellchecker_manager import SpellcheckerManager
    from core.saved_translations_manager import SavedTranslationsManager
    from ui.ui_updater import UIUpdater
    from handlers.list_selection_handler import ListSelectionHandler
    from handlers.text_operation_handler import TextOperationHandler
    from handlers.app_action_handler import AppActionHandler
    from handlers.project_action_handler import ProjectActionHandler
    from handlers.issue_scan_handler import IssueScanHandler
    from handlers.search_handler import SearchHandler
    from handlers.string_settings_handler import StringSettingsHandler
    from handlers.translation_handler import TranslationHandler
    from handlers.text_analysis_handler import TextAnalysisHandler
    from handlers.ai_chat_handler import AIChatHandler
    from handlers.bookmark_handler import BookmarkHandler
    from plugins.base_game_rules import BaseGameRules
    from components.editor.line_numbered_text_edit import LineNumberedTextEdit
    from components.custom_list_widget import CustomListWidget
    from components.search_panel import SearchPanelWidget

class UIProvider(Protocol):
    @property
    def statusBar(self) -> Optional[QStatusBar]: ...
    def force_focus(self) -> None: ...
    @property
    def preview_text_edit(self) -> 'LineNumberedTextEdit': ...
    @property
    def original_text_edit(self) -> 'LineNumberedTextEdit': ...
    @property
    def edited_text_edit(self) -> 'LineNumberedTextEdit': ...
    @property
    def block_list_widget(self) -> 'CustomListWidget': ...
    @property
    def search_panel_widget(self) -> 'SearchPanelWidget': ...
    @property
    def open_glossary_button(self) -> QPushButton: ...

class ProjectContext(Protocol):
    @property
    def state(self) -> 'StateManager': ...
    @property
    def data_store(self) -> 'AppDataStore': ...
    @property
    def project_manager(self) -> Optional['ProjectManager']: ...
    @property
    def settings_manager(self) -> 'SettingsManager': ...
    @property
    def data_processor(self) -> 'DataStateProcessor': ...
    @property
    def saved_translations_manager(self) -> 'SavedTranslationsManager': ...
    @property
    def ui_updater(self) -> 'UIUpdater': ...
    @property
    def undo_manager(self) -> 'UndoManager': ...
    @property
    def spellchecker_manager(self) -> 'SpellcheckerManager': ...
    
    # Handlers
    @property
    def list_selection_handler(self) -> 'ListSelectionHandler': ...
    @property
    def editor_operation_handler(self) -> 'TextOperationHandler': ...
    @property
    def app_action_handler(self) -> 'AppActionHandler': ...
    @property
    def project_action_handler(self) -> 'ProjectActionHandler': ...
    @property
    def issue_scan_handler(self) -> 'IssueScanHandler': ...
    @property
    def search_handler(self) -> 'SearchHandler': ...
    @property
    def string_settings_handler(self) -> 'StringSettingsHandler': ...
    @property
    def translation_handler(self) -> 'TranslationHandler': ...
    @property
    def text_analysis_handler(self) -> 'TextAnalysisHandler': ...
    @property
    def ai_chat_handler(self) -> 'AIChatHandler': ...
    @property
    def bookmark_handler(self) -> 'BookmarkHandler': ...
    
    @property
    def ui_provider(self) -> UIProvider: ...
    
    # Direct UI access shortcuts (MainWindow properties)
    @property
    def preview_text_edit(self) -> 'LineNumberedTextEdit': ...
    @property
    def original_text_edit(self) -> 'LineNumberedTextEdit': ...
    @property
    def edited_text_edit(self) -> 'LineNumberedTextEdit': ...
    @property
    def block_list_widget(self) -> 'CustomListWidget': ...
    @property
    def search_panel_widget(self) -> 'SearchPanelWidget': ...
    @property
    def open_glossary_button(self) -> QPushButton: ...
    
    # Data access shortcuts
    @property
    def data(self) -> List[Any]: ...
    @property
    def edited_file_data(self) -> List[Any]: ...
    @property
    def edited_data(self) -> Dict[Tuple[int, int], str]: ...
    
    @property
    def current_block_idx(self) -> int: ...
    @property
    def current_string_idx(self) -> int: ...
    
    @property
    def current_game_rules(self) -> Optional['BaseGameRules']: ...
    @property
    def active_game_plugin(self) -> Optional[str]: ...
    @property
    def block_to_project_file_map(self) -> Dict[int, int]: ...
    
    @property
    def unsaved_changes(self) -> bool: ...
    @unsaved_changes.setter
    def unsaved_changes(self, value: bool) -> None: ...

    def update_title(self) -> None: ...
    
    # UI actions & settings
    @property
    def autofix_enabled(self) -> Dict[str, bool]: ...
    @autofix_enabled.setter
    def autofix_enabled(self, value: Dict[str, bool]) -> None: ...
    @property
    def detection_enabled(self) -> Dict[str, bool]: ...
    @detection_enabled.setter
    def detection_enabled(self, value: Dict[str, bool]) -> None: ...
    
    @property
    def line_width_warning_threshold_pixels(self) -> int: ...
    @property
    def game_dialog_max_width_pixels(self) -> int: ...
    @property
    def show_width_guideline(self) -> bool: ...
    @property
    def spellchecker_enabled(self) -> bool: ...
    @property
    def spellchecker_language(self) -> str: ...
    
    @property
    def newline_display_symbol(self) -> str: ...
    @property
    def newline_color_rgba(self) -> str: ...
    @property
    def newline_bold(self) -> bool: ...
    @property
    def newline_italic(self) -> bool: ...
    @property
    def newline_underline(self) -> bool: ...
    @property
    def tag_color_rgba(self) -> str: ...
    @property
    def tag_bold(self) -> bool: ...
    @property
    def tag_italic(self) -> bool: ...
    @property
    def tag_underline(self) -> bool: ...
    @property
    def newline_css(self) -> str: ...
    @property
    def tag_css(self) -> str: ...
    @property
    def space_dot_color_hex(self) -> str: ...
    @property
    def preview_wrap_lines(self) -> bool: ...
    @property
    def editors_wrap_lines(self) -> bool: ...
    @property
    def bracket_tag_color_hex(self) -> str: ...
    
    @property
    def font_combobox(self) -> Optional[QComboBox]: ...
    @property
    def width_spinbox(self) -> Optional[QSpinBox]: ...
    @property
    def apply_width_button(self) -> Optional[QPushButton]: ...
    @property
    def auto_fix_button(self) -> Optional[QPushButton]: ...
    @property
    def ai_translate_button(self) -> Optional[QPushButton]: ...
    @property
    def ai_variation_button(self) -> Optional[QPushButton]: ...
    
    @property
    def status_label_part1(self) -> Optional[QWidget]: ...
    @property
    def status_label_part2(self) -> Optional[QWidget]: ...
    @property
    def status_label_part3(self) -> Optional[QWidget]: ...
    @property
    def plugin_status_label(self) -> Optional[QWidget]: ...
    @property
    def statusBar(self) -> Optional[QStatusBar]: ...
    
    @property
    def close_project_action(self) -> Optional[QAction]: ...
    
    # Additional properties needed by handlers
    @property
    def prompt_editor_enabled(self) -> bool: ...
    @property
    def string_metadata(self) -> Dict[Tuple[int, int], Any]: ...
    @property
    def current_font_map(self) -> Dict[str, Any]: ...
    @property
    def font_map(self) -> Dict[str, Any]: ...
    @property
    def lines_per_page(self) -> int: ...
    @property
    def default_tag_mappings(self) -> Dict[str, str]: ...
