from PyQt6.QtGui import QColor
from plugins.common.config_factory import generate_base_config

P_NEWLINE_MARKER = "▶"
L_NEWLINE_MARKER = "▷"
P_VISUAL_EDITOR_MARKER = "▶"
L_VISUAL_EDITOR_MARKER = "▷"

PROBLEM_WIDTH_EXCEEDED = "PKFR_WIDTH_EXCEEDED"
PROBLEM_SHORT_LINE = "PKFR_SHORT_LINE"
PROBLEM_EMPTY_SUBLINE = "PKFR_EMPTY_SUBLINE"
PROBLEM_SINGLE_WORD_SUBLINE = "PKFR_SINGLE_WORD_SUBLINE"
PROBLEM_SINGLE_WORD_SUBLINE_NON_START = "PKFR_SINGLE_WORD_SUBLINE_NON_START"
PROBLEM_TAG_WARNING = "PKFR_TAG_WARNING"
PROBLEM_BAD_SPACING = "PKFR_BAD_SPACING"
PROBLEM_MISSING_ICON_SPACING = "PKFR_MISSING_ICON_SPACING"

# Keep compatibility with base rule references
PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY = "PKFR_EMPTY_ODD_SUBLINE_DISPLAY"

PRIORITY_WIDTH_EXCEEDED = 1
PRIORITY_TAG_WARNING = 2
PRIORITY_EMPTY_SUBLINE = 3
PRIORITY_SINGLE_WORD_SUBLINE = 4
PRIORITY_SINGLE_WORD_SUBLINE_NON_START = 3
PRIORITY_SHORT_LINE = 5

custom_problems = {
    "EMPTY_SUBLINE": {
        "name": "Empty Subline",
        "color": QColor(255, 165, 0, 180),
        "priority": PRIORITY_EMPTY_SUBLINE,
        "description": "An empty subline created by two consecutive newline tags is present."
    }
}

overrides = {
    "priorities": {
        "WIDTH_EXCEEDED": PRIORITY_WIDTH_EXCEEDED,
        "TAG_WARNING": PRIORITY_TAG_WARNING,
        "SINGLE_WORD_SUBLINE": PRIORITY_SINGLE_WORD_SUBLINE,
        "SINGLE_WORD_SUBLINE_NON_START": PRIORITY_SINGLE_WORD_SUBLINE_NON_START,
        "SHORT_LINE": PRIORITY_SHORT_LINE,
    },
    "colors": {
        "WIDTH_EXCEEDED": QColor(255, 0, 0, 100),
        "TAG_WARNING": QColor(255, 255, 0, 80),
        "SHORT_LINE": QColor(0, 200, 0, 100),
        "SINGLE_WORD_SUBLINE": QColor(0, 0, 255, 120),
        "SINGLE_WORD_SUBLINE_NON_START": QColor(139, 69, 19, 120),
    }
}

PROBLEM_DEFINITIONS, DEFAULT_DETECTION_SETTINGS, DEFAULT_AUTOFIX_SETTINGS = generate_base_config(
    "PKFR", overrides=overrides, custom_problems=custom_problems
)

# Exclude ZMC/ZWW EMPTY_ODD_SUBLINE_DISPLAY as PKFR uses PROBLEM_EMPTY_SUBLINE instead
if PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY in PROBLEM_DEFINITIONS:
    del PROBLEM_DEFINITIONS[PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY]
if PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY in DEFAULT_DETECTION_SETTINGS:
    del DEFAULT_DETECTION_SETTINGS[PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY]
if PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY in DEFAULT_AUTOFIX_SETTINGS:
    del DEFAULT_AUTOFIX_SETTINGS[PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY]

# PKFR_EMPTY_SUBLINE has auto-fix set to True by default
DEFAULT_AUTOFIX_SETTINGS[PROBLEM_EMPTY_SUBLINE] = True

DEFAULT_TAG_MAPPINGS_POKEMON_FR = {
    "{PLAYER}": "{PLAYER}",
    "{RIVAL}": "{RIVAL}",
    "{DPAD_UPDOWN}": "{DPAD_UPDOWN}",
    "{A_BUTTON}": "{A_BUTTON}",
    "{B_BUTTON}": "{B_BUTTON}",
    "{DPAD_LEFTRIGHT}": "{DPAD_LEFTRIGHT}",
    "{PLUS}": "{PLUS}",
    "{START_BUTTON}": "{START_BUTTON}",
    "{NO}": "{NO}",
    "{LV_2}": "{LV_2}",
    "{ID}": "{ID}",
    "{PP}": "{PP}",
    "{ESCAPE 0x03}": "{ESCAPE 0x03}",
    "{ID}{NO}": "{ID}{NO}",
    "{PKMN}": "{PKMN}"
}

CONTROL_CODES = ["\\p", "\\l", "\\n"]