"""Smoke tests for the Wii System Font plugin. Generated by tools/new_plugin.py; extend freely."""
from plugins.testing import check_loads, check_round_trip, check_validator

PLUGIN = "wii_sysfont"
# A small piece of the game's text in the form the plugin loads. Replace it with a real sample.
SAMPLE = "First line\nSecond line\n\nA line of the next block"


def test_the_plugin_loads():
    check_loads(PLUGIN)


def test_the_sample_survives_load_and_save():
    check_round_trip(PLUGIN, SAMPLE)


def test_the_validator_passes():
    check_validator(PLUGIN)
