from plugins.common.config_factory import generate_base_config

PLUGIN_PREFIX = "DEFAULT"

PROBLEM_TAG_WARNING = f"{PLUGIN_PREFIX}_TAG_WARNING"
PROBLEM_WIDTH_EXCEEDED = f"{PLUGIN_PREFIX}_WIDTH_EXCEEDED"
PROBLEM_SHORT_LINE = f"{PLUGIN_PREFIX}_SHORT_LINE"
PROBLEM_EMPTY_ODD_SUBLINE_DISPLAY = f"{PLUGIN_PREFIX}_EMPTY_ODD_SUBLINE_DISPLAY"
PROBLEM_SINGLE_WORD_SUBLINE = f"{PLUGIN_PREFIX}_SINGLE_WORD_SUBLINE"
PROBLEM_SINGLE_WORD_SUBLINE_NON_START = f"{PLUGIN_PREFIX}_SINGLE_WORD_SUBLINE_NON_START"
PROBLEM_EMPTY_FIRST_LINE_OF_PAGE = f"{PLUGIN_PREFIX}_EMPTY_FIRST_LINE_OF_PAGE"
PROBLEM_BAD_SPACING = f"{PLUGIN_PREFIX}_BAD_SPACING"
PROBLEM_MISSING_ICON_SPACING = f"{PLUGIN_PREFIX}_MISSING_ICON_SPACING"
PROBLEM_BROKEN_ICON_HYPHEN = f"{PLUGIN_PREFIX}_BROKEN_ICON_HYPHEN"

CONTROL_CODES = []
DEFAULT_LINES_PER_PAGE = 4

PROBLEM_DEFINITIONS, DEFAULT_DETECTION_SETTINGS, DEFAULT_AUTOFIX_SETTINGS = generate_base_config(
    PLUGIN_PREFIX,
    overrides={
        "autofix_settings": {
            "TAG_WARNING": False,
            "SINGLE_WORD_SUBLINE": False,
            "SINGLE_WORD_SUBLINE_NON_START": False,
        }
    },
)

