"""Front matter of the documents and docs/INDEX.md, the one-line-per-document map.

Every document under ``docs/`` (the history and the audit excepted) starts with

    ---
    status: current | design | archive
    updated: 2026-10-02
    owns: the code or the question it is the home of
    tokens: 2.4k
    purpose: one line (English pages only; a uk/ page is the translation of its twin)
    ---

``python tools/docs_index.py --write`` refreshes ``tokens`` in every header and
rebuilds ``docs/INDEX.md`` from the headers; ``--check`` says whether that is
needed. The index is what an agent reads to decide which document to open.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parent.parent
INDEX = "docs/INDEX.md"
DOC_GLOBS = ("docs/*.md", "docs/wiki/*.md", "docs/wiki/uk/*.md")
# Generated by something else; they carry no header and are listed below.
NO_HEADER = {INDEX, "docs/PLUGIN_CONTRACT.md"}
FIELDS = ("status", "updated", "owns", "tokens", "purpose")
STATUSES = ("current", "design", "archive")

# Documents outside docs/ and the generated ones: (path, purpose, status, owns).
EXTRA: Tuple[Tuple[str, str, str, str], ...] = (
    ("AGENTS.md", "Agent entry: hard rules, commands, checklist", "current", "everything"),
    ("README.md", "Pitch, install, run, tests, doc map", "current", "repository"),
    ("CHANGELOG.md", "One line per change; grep below [Unreleased]", "current", "releases"),
    ("plan.md, task.md, walkthrough.md", "The work package in progress (Ukrainian)", "current", "current iteration"),
    ("docs/PLUGIN_CONTRACT.md", "Every plugin hook; generated from plugins/spec.py", "current", "plugins/spec.py"),
    ("docs/audit/2026-10-01/", "Audit reports A-F, PLAN, TASKS", "current", "the 2026-10 audit"),
    ("docs/history/", "Frozen logs. Do not read; grep only", "archive", "past iterations"),
    ("plugins/default_plugin/AI_PLUGIN_ASSISTANT_PROMPT.md", "Interview an AI runs before writing a plugin", "current", "plugins/"),
    ("plugins/default_plugin/README.md", "Pointer to the plugin guide", "current", "plugins/default_plugin"),
    ("plugins/script_template.md, plugins/script_preparation_guideline.md", "Walkthrough script format", "current", "core/script_markup"),
    ("plugins/zelda_bmg/TAGS.md", "Twilight Princess tag reference (large)", "current", "plugins/zelda_bmg"),
    ("companion/README.md", "Companion server setup", "current", "companion/"),
    ("tools/i18n-translate/README.md", "Interface translation tool", "current", "tools/i18n-translate"),
)


def estimate_tokens(text: str) -> int:
    """A rough token count: Latin text ~3.8 characters per token, anything else ~2.3."""
    ascii_chars = sum(1 for char in text if ord(char) < 128)
    return round(ascii_chars / 3.8 + (len(text) - ascii_chars) / 2.3)


def format_tokens(count: int) -> str:
    return f"{max(0.1, round(count / 1000, 1)):.1f}k"


def parse_tokens(value: str) -> int:
    return round(float(value.rstrip("k")) * 1000)


def split_header(text: str) -> Tuple[Dict[str, str], str]:
    """``(header fields, body)``; no header gives ``({}, text)``."""
    found = re.match(r"\A---\n(.*?)\n---\n", text, re.S)
    if not found:
        return {}, text
    fields: Dict[str, str] = {}
    for line in found.group(1).splitlines():
        key, separator, value = line.partition(":")
        if separator:
            fields[key.strip()] = value.strip()
    return fields, text[found.end():]


def join_header(fields: Dict[str, str], body: str) -> str:
    lines = [f"{key}: {fields[key]}" for key in FIELDS if fields.get(key)]
    return "---\n" + "\n".join(lines) + "\n---\n" + body


def documents() -> List[str]:
    found = set()
    for pattern in DOC_GLOBS:
        found.update(path.relative_to(ROOT).as_posix() for path in ROOT.glob(pattern))
    return sorted(found - NO_HEADER)


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8").replace("\r\n", "\n")


def _write(path: str, text: str) -> None:
    target = ROOT / path
    crlf = target.exists() and b"\r\n" in target.read_bytes()
    target.write_bytes(text.replace("\n", "\r\n" if crlf else "\n").encode("utf-8"))


def refreshed(path: str) -> str:
    """The document with its ``tokens`` field brought up to date."""
    fields, body = split_header(read(path))
    fields["tokens"] = format_tokens(estimate_tokens(body))
    return join_header(fields, body)


def problems(path: str) -> List[str]:
    """What is wrong with the header of one document."""
    fields, body = split_header(read(path))
    if not fields:
        return [f"{path}: no header"]
    found = []
    is_translation = path.startswith("docs/wiki/uk/")
    for key in FIELDS:
        if key == "purpose" and is_translation:
            continue
        if not fields.get(key):
            found.append(f"{path}: header has no '{key}'")
    if fields.get("status") and fields["status"] not in STATUSES:
        found.append(f"{path}: status '{fields['status']}' is not one of {', '.join(STATUSES)}")
    if fields.get("tokens"):
        stated, real = parse_tokens(fields["tokens"]), estimate_tokens(body)
        if abs(stated - real) > max(150, 0.2 * real):
            found.append(f"{path}: header says {fields['tokens']}, the text is about {format_tokens(real)}")
    return found


def _link(path: str) -> str:
    # The path alone: a link would spell every path twice, and the index is read for the paths.
    return ", ".join(f"`{part.strip()}`" for part in path.split(","))


def render_index() -> str:
    rows = []
    for path in documents():
        if path.startswith("docs/wiki/uk/"):
            continue
        fields, _body = split_header(read(path))
        twin = "docs/wiki/uk/" + path[len("docs/wiki/"):]
        name = _link(path) + (" (+uk)" if path.startswith("docs/wiki/") and (ROOT / twin).exists() else "")
        rows.append((name, fields.get("purpose", ""), fields.get("tokens", ""), fields.get("status", ""), fields.get("owns", "")))
    for path, purpose, status, owns in EXTRA:
        rows.append((_link(path), purpose, "", status, owns))
    lines = [
        "# Documentation index",
        "",
        "Generated by `python tools/docs_index.py --write` from the header of each document; do not edit by hand.",
        "Status: `current` describes the code as it is; `design` describes a target; `archive` is history.",
        "Read the row, then open only the document you need.",
        "",
        "| Document | What it is the home of | ~tokens | Status | Owns |",
        "|---|---|---|---|---|",
    ]
    lines += [f"| {name} | {purpose} | {tokens} | {status} | {owns} |" for name, purpose, tokens, status, owns in rows]
    return "\n".join(lines) + "\n"


def check() -> List[str]:
    found: List[str] = []
    for path in documents():
        found.extend(problems(path))
    index = ROOT / INDEX
    if not index.exists() or index.read_text(encoding="utf-8").replace("\r\n", "\n") != render_index():
        found.append(f"{INDEX} is out of date: run python tools/docs_index.py --write")
    return found


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="refresh token counts and rebuild docs/INDEX.md")
    group.add_argument("--check", action="store_true", help="report what --write would change")
    arguments = parser.parse_args(argv)
    if arguments.write:
        for path in documents():
            if split_header(read(path))[0]:
                _write(path, refreshed(path))
        _write(INDEX, render_index())
    found = check()
    for line in found:
        print(line)
    return 1 if found else 0


if __name__ == "__main__":
    sys.exit(main())
