"""Create a new game plugin from the template.

    python tools/new_plugin.py <id> "<Display Name>" --prefix XX

``<id>`` is the folder name under ``plugins/`` (lowercase letters, digits,
underscores). ``--prefix`` is the short uppercase tag in front of the plugin's
problem ids (``XX_WIDTH_EXCEEDED``); it must not be used by another plugin.

The result is a plugin the application lists at once, with a test file under
``tests/test_plugins/test_<id>/`` that already passes. Then:

    python -m plugins.validate <id>
    python -m pytest tests/test_plugins/test_<id>/

and replace the parser in ``rules.py``, the tags in ``tag_manager.py`` and the
font files with the game's own.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import List, Sequence, Set

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = "default_plugin"
TEMPLATE_PREFIX = "DEFAULT"
TEMPLATE_DISPLAY_NAME = "Default Plugin Template"
# Files that describe the template itself, or belong to one user.
NOT_COPIED = {"__pycache__", "README.md", "AI_PLUGIN_ASSISTANT_PROMPT.md", "aliases.json"}

TEST_FILE = '''"""Smoke tests for the {display_name} plugin. Generated by tools/new_plugin.py; extend freely."""
from plugins.testing import check_loads, check_round_trip, check_validator

PLUGIN = "{plugin_id}"
# A small piece of the game's text in the form the plugin loads. Replace it with a real sample.
SAMPLE = "First line\\nSecond line\\n\\nA line of the next block"


def test_the_plugin_loads():
    check_loads(PLUGIN)


def test_the_sample_survives_load_and_save():
    check_round_trip(PLUGIN, SAMPLE)


def test_the_validator_passes():
    check_validator(PLUGIN)
'''


class NewPluginError(ValueError):
    """The request cannot be carried out; the message says why."""


def used_prefixes(plugins_dir: Path) -> Set[str]:
    """Problem-id prefixes of the plugins that exist (read from their config.py and config.json)."""
    prefixes: Set[str] = set()
    for module_path in plugins_dir.glob("*/config.py"):
        try:
            source = module_path.read_text(encoding="utf-8")
        except OSError:
            continue
        prefixes.update(re.findall(r'generate_base_config\(\s*"([A-Z][A-Z0-9]*)"', source))
        prefixes.update(re.findall(r'PLUGIN_PREFIX\s*=\s*"([A-Z][A-Z0-9]*)"', source))
    for config_path in plugins_dir.glob("*/config.json"):
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        for key in list(config.get("autofix_enabled") or {}) + list(config.get("detection_enabled") or {}):
            match = re.match(r"([A-Z][A-Z0-9]*)_", str(key))
            if match:
                prefixes.add(match.group(1))
    return prefixes


def create_plugin(
    plugin_id: str,
    display_name: str,
    prefix: str,
    plugins_dir: Path = ROOT / "plugins",
    tests_dir: Path = ROOT / "tests" / "test_plugins",
) -> List[Path]:
    """Create ``plugins/<plugin_id>`` and its test folder. Returns the files written."""
    display_name = display_name.strip()
    if not re.fullmatch(r"[a-z][a-z0-9_]*", plugin_id):
        raise NewPluginError("the id must be lowercase letters, digits and underscores, starting with a letter")
    if not re.fullmatch(r"[A-Z][A-Z0-9]*", prefix):
        raise NewPluginError("the prefix must be uppercase letters and digits, starting with a letter")
    if not display_name:
        raise NewPluginError("the display name is empty")
    template = plugins_dir / TEMPLATE
    target = plugins_dir / plugin_id
    test_target = tests_dir / f"test_{plugin_id}"
    if not template.is_dir():
        raise NewPluginError(f"the template {template} is missing")
    if target.exists():
        raise NewPluginError(f"{target} already exists")
    if test_target.exists():
        raise NewPluginError(f"{test_target} already exists")
    if prefix in used_prefixes(plugins_dir):
        raise NewPluginError(f"the prefix {prefix} is already used by another plugin")

    shutil.copytree(template, target, ignore=lambda _directory, names: [n for n in names if n in NOT_COPIED])

    config_path = target / "config.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    config["display_name"] = display_name
    for section in ("autofix_enabled", "detection_enabled"):
        config[section] = {
            re.sub(rf"^{TEMPLATE_PREFIX}_", f"{prefix}_", key): value
            for key, value in (config.get(section) or {}).items()
        }
    config_path.write_text(json.dumps(config, ensure_ascii=False, indent=4) + "\n", encoding="utf-8", newline="\n")

    _replace(target / "config.py", (f'PLUGIN_PREFIX = "{TEMPLATE_PREFIX}"', f'PLUGIN_PREFIX = "{prefix}"'))
    _replace(
        target / "rules.py",
        (f'return "{TEMPLATE_DISPLAY_NAME}"', f"return {json.dumps(display_name, ensure_ascii=False)}"),
        ('"default_plugin_script.md"', f'"{plugin_id}_script.md"'),
        ('"""Minimal, copy-ready plugin template.', f'"""{display_name}. Generated from plugins/{TEMPLATE}.'),
    )

    test_target.mkdir(parents=True)
    (test_target / "__init__.py").write_text("", encoding="utf-8")
    (test_target / "test_rules.py").write_text(
        TEST_FILE.format(display_name=display_name.replace('"', "'"), plugin_id=plugin_id),
        encoding="utf-8",
        newline="\n",
    )
    return sorted(p for p in [*target.rglob("*"), *test_target.rglob("*")] if p.is_file())


def _replace(path: Path, *pairs: Sequence[str]) -> None:
    text = path.read_text(encoding="utf-8")
    for old, new in pairs:
        if old not in text:
            raise NewPluginError(f"the template changed: {path.name} no longer contains {old!r}")
        text = text.replace(old, new, 1)
    path.write_text(text, encoding="utf-8", newline="\n")


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(description="Create a new game plugin from the template.")
    parser.add_argument("plugin_id", help="folder name under plugins/, e.g. fire_emblem")
    parser.add_argument("display_name", help='name shown in the application, e.g. "Fire Emblem"')
    parser.add_argument("--prefix", required=True, help="uppercase prefix of the plugin's problem ids, e.g. FE")
    arguments = parser.parse_args(list(argv))
    try:
        written = create_plugin(arguments.plugin_id, arguments.display_name, arguments.prefix)
    except NewPluginError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    for path in written:
        print(path.relative_to(ROOT).as_posix())
    print(
        f"\nCreated plugin '{arguments.plugin_id}'. Next:\n"
        f"  python -m plugins.validate {arguments.plugin_id}\n"
        f"  python -m pytest tests/test_plugins/test_{arguments.plugin_id}/\n"
        f"then replace the parser in plugins/{arguments.plugin_id}/rules.py with the game's own."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
